In [2]:
import numpy as np
import pandas as pd

In [8]:
dct = { f'col_{i}': [i*1, i*2, i*3, i*4, i*5] if i != 3 else [i, i, i, i, i] for i in range(5) }
dct

{'col_0': [0, 0, 0, 0, 0],
 'col_1': [1, 2, 3, 4, 5],
 'col_2': [2, 4, 6, 8, 10],
 'col_3': [3, 3, 3, 3, 3],
 'col_4': [4, 8, 12, 16, 20]}

In [12]:
df = pd.DataFrame(dct)
df

   col_0  col_1  col_2  col_3  col_4
0      0      1      2      3      4
1      0      2      4      3      8
2      0      3      6      3     12
3      0      4      8      3     16
4      0      5     10      3     20

In [ ]:
DataFrame.apply( func, axis = 0, raw = False, result_type = None, args = (), **kwargs )
Series.apply( func, args=(), **kwargs )

In [14]:
df.apply(np.min)

col_0    0
col_1    1
col_2    2
col_3    3
col_4    4
dtype: int64

In [19]:
def my_func(series):
    return (series + 100) if series.name != 'col_2' else series * 0

In [21]:
df.apply(my_func)

   col_0  col_1  col_2  col_3  col_4
0    100    101      0    103    104
1    100    102      0    103    108
2    100    103      0    103    112
3    100    104      0    103    116
4    100    105      0    103    120

In [26]:
df.apply(np.mean) # среднее по столбцам

col_0     0.0
col_1     3.0
col_2     6.0
col_3     3.0
col_4    12.0
dtype: float64

In [28]:
df.apply(np.mean, axis = 1) # среднее по строкам

0    2.0
1    3.4
2    4.8
3    6.2
4    7.6
dtype: float64

In [34]:
dict_array = {'age': [53, 25, 11, 18, 7],
              'name': ['Фамилия_1 Имя_1', 'Фамилия_2 Имя_2 Отчество_2', 'Фамилия_3 Имя_3', 'Фамилия_4 Имя_4', 'Фамилия_5 Имя_5'],
              'наличие авто': [True, True, False, True, False]}

df= pd.DataFrame(dict_array)
df

   age                        name  наличие авто
0   53             Фамилия_1 Имя_1          True
1   25  Фамилия_2 Имя_2 Отчество_2          True
2   11             Фамилия_3 Имя_3         False
3   18             Фамилия_4 Имя_4          True
4    7             Фамилия_5 Имя_5         False

In [36]:
df['name']

0               Фамилия_1 Имя_1
1    Фамилия_2 Имя_2 Отчество_2
2               Фамилия_3 Имя_3
3               Фамилия_4 Имя_4
4               Фамилия_5 Имя_5
Name: name, dtype: object

In [38]:
'Фамилия_2 Имя_2 Отчество_2'.split(' ')

['Фамилия_2', 'Имя_2', 'Отчество_2']